(key-chord-define-global "/s" 'swiper)
(key-chord-define-global "/r" 'isearch-backward)
(key-chord-define-global "/x" 'counsel-M-x)
(key-chord-define-global "/f" 'projectile--find-file)
(key-chord-define-global ",a" 'windmove-left)
(key-chord-define-global ",w" 'windmove-up)
(key-chord-define-global ",d" 'windmove-down)
(key-chord-define-global ",f" 'windmove-right)
(key-chord-define-global ",s" 'save-buffer)
(key-chord-define-global ",z" 'repeat)
(key-chord-define-global "FF" 'counsel-find-file)
(global-set-key (kbd "<escape>") 'keyboard-escape-quit)
